export const ADD_DEVICE = 'WS.ADD_DEVICE';
export const REMOVE_DEVICE = 'WS.REMOVE_DEVICE';
export const SET_CLIENT_SOCKET = 'WS.SET_CLIENT_SOCKET';
export const RESET_DEVICES = 'WS.RESET_DEVICES';
export default { ADD_DEVICE, REMOVE_DEVICE, SET_CLIENT_SOCKET, RESET_DEVICES };
